Update 'post-start' and 'drain' according to recommendations added to the documentation

diff --git a/jobs/paragon/templates/drain b/jobs/paragon/templates/drain
--- a/jobs/paragon/templates/drain
+++ b/jobs/paragon/templates/drain
@@ -1,9 +1,32 @@
 #!/usr/bin/env bash
 
-# If a command fails, exit immediately
-set -e
+# If a command fails, in a pipeline or not, exit immediately
+set -e -o pipefail
 
-# blocks until drained
+function prepend_datetime() {
+  awk -W interactive '{ system("echo -n [$(date +%FT%T%z)]"); print " " $0 }'
+}
+
+# Before redirecting stdout and stderr, copy the file descriptor for original
+# stdout where BOSH is expecting an integer, and only that.
+exec 3>&1
+exec \
+    1> >(prepend_datetime >> /var/vcap/sys/log/paragon/drain.out.log) \
+    2> >(prepend_datetime >> /var/vcap/sys/log/paragon/drain.err.log)
+
+output_for_bosh() {
+    exit_code=$?
+
+    if [ $exit_code -eq 0 ]; then
+        echo "paragon process is properly drained"
+    else
+        echo "drain failed"
+    fi
+
+    echo $exit_code >&3
+}
+
+trap output_for_bosh EXIT
+
+# blocks until drained, with a 10 minutes timeout
 curl -sf --max-time 600 -X POST https://127.0.0.1:6060/admin/drain
-
-echo 0
